### ISSUE TITLE
[Insight] Text files should end with a newline character

### ISSUE THREAD

**Issue by remymandit** [remymandit/DeclareNounou#39]
**[in app/config/config_dev.yml, line 37](https://github.com/remymandit/DeclareNounou/blob/master/app/config/config_dev.yml#L37)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
assetic:
    use_controller: true

swiftmailer:
# en mode dev tous les messages seront envoyés à cette adresse
    delivery_address: toto@example.fr
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/212ef98e-d99e-44b9-9fb1-8bdc2c701cb8/analyses/25)_
