### ISSUE TITLE
[Insight] Text files should end with a newline character

### ISSUE THREAD

**Issue by remymandit** [remymandit/DeclareNounou#40]
**[in app/config/config.yml, line 87](https://github.com/remymandit/DeclareNounou/blob/master/app/config/config.yml#L87)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: DeclareNounou\UserBundle\Entity\User
    group:
        group_class: DeclareNounou\UserBundle\Entity\Group
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/212ef98e-d99e-44b9-9fb1-8bdc2c701cb8/analyses/25)_
