### ISSUE TITLE
[Insight] Text files should end with a newline character

### ISSUE THREAD

**Issue by remymandit** [remymandit/DeclareNounou#41]
**[in app/config/routing.yml, line 40](https://github.com/remymandit/DeclareNounou/blob/master/app/config/routing.yml#L40)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    defaults: { _locale: fr }
    requirements:
        _locale: fr
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/212ef98e-d99e-44b9-9fb1-8bdc2c701cb8/analyses/25)_
