### ISSUE TITLE
[Insight] Text files should end with a newline character

### ISSUE THREAD

**Issue by remymandit** [remymandit/DeclareNounou#48]
**[in src/DeclareNounou/GestNounouBundle/Resources/config/routing.yml, line 20](https://github.com/remymandit/DeclareNounou/blob/master/src/DeclareNounou/GestNounouBundle/Resources/config/routing.yml#L20)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
    resource: "@DeclareNounouGestNounouBundle/Resources/config/routing/contrat.yml"
    prefix: /contrat

DeclareNounouGestNounouBundel_pointage:
    resource: "@DeclareNounouGestNounouBundle/Resources/config/routing/pointage.yml"
    prefix: /pointage
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/212ef98e-d99e-44b9-9fb1-8bdc2c701cb8/analyses/25)_
