### ISSUE TITLE
[Insight] Text files should end with a newline character - in src/DeclareNounou/…/config/services.yml, line 16

### ISSUE THREAD

**Issue by remymandit** [remymandit/DeclareNounou#65]
**[in src/DeclareNounou/UserBundle/Resources/config/services.yml, line 16](https://github.com/remymandit/DeclareNounou/blob/master/src/DeclareNounou/UserBundle/Resources/config/services.yml#L16)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
        arguments: [@declarenounou.invitation.form.data_transformer]
        tags: [{ name: "form.type", alias: "declarenounou_invitation_type" }]

    declarenounou.invitation.form.data_transformer:
        class: DeclareNounou\UserBundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: [@doctrine]
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/212ef98e-d99e-44b9-9fb1-8bdc2c701cb8/analyses/30?status=violations)_
